linux_hardening_disable_root_ssh: true
linux_hardening_password_auth: false
linux_hardening_fail2ban_enabled: true
linux_hardening_unattended_upgrades: true
linux_hardening_ntp_servers:
  - 0.pool.ntp.org
  - 1.pool.ntp.org
